version: '3.7'

services:
  django:
    extends:
      file: docker-compose.yml
      service: django
    image: watchdog-django-test
    working_dir: /app/services/backend
    build:
      dockerfile: ./compose/test/django/Dockerfile



